eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    enabled: true
    propagation:
      consume: W3C,B3,B3_MULTI
      produce: W3C
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
