spring:
  data:
    mongodb:
      uri: mongodb://gabriel:gabriel@localhost:27017/customer?authSource=admin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
