spring:
  mongodb:
    username: gabriel
    password: gabriel
    host: ms_mongo_db
    port: 27017
    database: customer
    authentication-database: admin
eureka:
  instance:
    hostname: customer-service
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8090