spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak-ms:8080/realms/micro-services"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
        - id: product-service-openapi
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/aggregate/product-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: customer-service-openapi
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/aggregate/customer-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: order-service-openapi
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/aggregate/order-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: payment-service-openapi
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/aggregate/payment-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Customer Service
        url: /aggregate/customer-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Payment Service
        url: /aggregate/payment-service/v3/api-docs
    urls-primary-name: Order Service
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: B3,W3C
    baggage:
      - traceId
      - spanId
    baggage-correlation:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
server:
  port: 8222
