spring:
  datasource:
    url: jdbc:postgresql://ms_pg_sql:5432/order
    username: gabriel
    password: gabriel
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: ms_kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.gabriel.ecommerce.kafka.OrderConfirmation

server:
  port: 8070

application:
  config:
    customer-url: http://customer-service:8222/api/v1/customers
    payment-url: http://payment-service:8222/api/v1/payments
    product-url: http://product-service:8222/api/v1/products
