spring:
  datasource:
    url: jdbc:postgresql://ms_pg_sql:5432/payment
    username: gabriel
    password: gabriel
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ms_kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentNotificationRequest:com.gabriel.ecommerce.notification.PaymentNotificationRequest

server:
  port: 8060
